In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.4'

## Create & Read

#### 1D Array

In [4]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(5,)

In [7]:
arr1.dtype

dtype('int64')

In [8]:
arr1.ndim

1

In [9]:
arr1.size

5

#### 2D Array

In [11]:
arr2 = np.array([[1, 4, 5], [6, 7, 4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [12]:
arr2.ndim

2

In [14]:
arr2.shape # (row, column)

(2, 3)

In [15]:
arr2.dtype

dtype('int64')

In [16]:
arr2.size

6

#### 3D Array

In [17]:
arr3 = np.array([[[1, 4, 5], [6, 7, 4]], [[3, 5, 4], [5, 8, 6]]])
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 6]]])

In [18]:
arr3.ndim

3

In [19]:
arr3.shape

(2, 2, 3)

In [20]:
arr3.size

12

### Create Random Array

In [21]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.79749824, 0.3864072 , 0.82697694],
        [0.76751393, 0.82106316, 0.72588674]],

       [[0.62838213, 0.28788248, 0.16292615],
        [0.7200911 , 0.51647417, 0.44654028]],

       [[0.25811902, 0.20781629, 0.27436368],
        [0.39368416, 0.35544937, 0.01389061]]])

In [22]:
randomArr.dtype

dtype('float64')

In [24]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
zeroes.ndim

3

In [30]:
full = np.full((3, 2, 3), 9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [28]:
full.dtype

dtype('int64')

In [29]:
full.size

18

In [31]:
arr3[1, 0, 1]

np.int64(5)

### Update & Delete

In [32]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [33]:
a1

array([[[0.21817195, 0.50636712],
        [0.80696403, 0.90388253],
        [0.56696151, 0.93806464]],

       [[0.44455819, 0.01526407],
        [0.43940225, 0.56586261],
        [0.33249433, 0.63470783]]])

In [36]:
a2

array([[[7.00552239e-01, 4.79078604e-01],
        [8.40618494e-01, 6.75907922e-05],
        [8.50249155e-01, 8.97962524e-01]],

       [[1.61292327e-01, 2.65384064e-01],
        [4.55012056e-01, 6.21138555e-01],
        [1.24168786e-01, 6.57721436e-01]]])

#### Basic Math Operations

In [37]:
np.add(a1, a2)

array([[[0.91872419, 0.98544573],
        [1.64758253, 0.90395012],
        [1.41721066, 1.83602716]],

       [[0.60585052, 0.28064814],
        [0.8944143 , 1.18700117],
        [0.45666312, 1.29242926]]])

In [38]:
np.subtract(a1, a2)

array([[[-0.48238029,  0.02728852],
        [-0.03365446,  0.90381494],
        [-0.28328765,  0.04010212]],

       [[ 0.28326587, -0.25011999],
        [-0.01560981, -0.05527595],
        [ 0.20832555, -0.02301361]]])

In [39]:
np.divide(a1, a2)

array([[[3.11428523e-01, 1.05696042e+00],
        [9.59964641e-01, 1.33728649e+04],
        [6.66818078e-01, 1.04465901e+00]],

       [[2.75622654e+00, 5.75169138e-02],
        [9.65693639e-01, 9.11008671e-01],
        [2.67776099e+00, 9.65010098e-01]]])

In [40]:
np.multiply(a1, a2)

array([[[1.52840847e-01, 2.42589655e-01],
        [6.78348889e-01, 6.10941365e-05],
        [4.82058542e-01, 8.42346892e-01]],

       [[7.17038253e-02, 4.05084155e-03],
        [1.99933320e-01, 3.51479084e-01],
        [4.12854177e-02, 4.17460944e-01]]])

In [41]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2, 8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [42]:
sqrt

np.float64(5.0)

In [43]:
abs

np.int64(2)

In [44]:
power

np.int64(256)

In [45]:
log

np.float64(3.2188758248682006)

In [46]:
mins

np.float64(0.015264072341273027)

In [47]:
maxs

np.float64(0.8979625239250293)

#### Update

In [48]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 6]]])

In [49]:
arr3[0, 0, 2] = 500

In [50]:
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   6]]])

In [51]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   6,   8]]])

In [52]:
# Reshape
arr3.shape

(2, 2, 3)

In [53]:
arr3_reshape = arr3.reshape(2, 3, 2)

In [54]:
arr3_reshape

array([[[  1,   4],
        [500,   4],
        [  6,   7]],

       [[  3,   4],
        [  5,   5],
        [  6,   8]]])

#### Appending & Inserting

In [55]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [56]:
# Create a new array
new_array = np.ones((3, 2, 3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [57]:
appd = np.append(zeroes, new_array, axis=0)

In [58]:
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [59]:
appd = np.append(zeroes, new_array, axis=1)
appd

array([[[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [60]:
# Insert

In [61]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [62]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [64]:
inserted_array = np.insert(zeroes, 1, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### Delete

In [65]:
arr4 = np.random.rand(3, 2, 3)

In [66]:
arr4

array([[[0.13244888, 0.25429734, 0.72676178],
        [0.33810224, 0.31181646, 0.78621713]],

       [[0.38010708, 0.2813947 , 0.64688684],
        [0.84165605, 0.63214025, 0.82954948]],

       [[0.94052869, 0.02822694, 0.25990465],
        [0.94893021, 0.48948338, 0.03722485]]])

In [68]:
# delete the array
arr5 = np.delete(arr4, 0, axis=1)

In [69]:
arr5

array([[[0.33810224, 0.31181646, 0.78621713]],

       [[0.84165605, 0.63214025, 0.82954948]],

       [[0.94893021, 0.48948338, 0.03722485]]])

In [70]:
np.save("new_array", arr5)

In [71]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [72]:
np.load("new_array.npy")

array([[[0.33810224, 0.31181646, 0.78621713]],

       [[0.84165605, 0.63214025, 0.82954948]],

       [[0.94893021, 0.48948338, 0.03722485]]])